### ISSUE TITLE
Drawn to Life: the Next Chapter throws an index out of bounds error

### ISSUE THREAD

**Issue by AftDawn** [lifehackerhansol/YANBF#4]
```
Tue Jan 18 2022 23:30:24 GMT+1100 (Australian Eastern Daylight Time): Extracting icon...
Resizing icon...
Extracting game metadata...
Creating SMDH...

Tue Jan 18 2022 23:30:24 GMT+1100 (Australian Eastern Daylight Time): Traceback (most recent call last):
  File "/home/aftdawn/YANBF/generator/generator.py", line 144, in <module>
    bannertoolarg += f'-p "{eng_title[2]}" -jp "{jpn_title[2]}" -fp "{fra_title[2]}" -gp "{ger_title[2]}" -ip "{ita_title[2]}" -sp "{spa_title[2]}" '
IndexError: list index out of range
```
Non of my other games give any errors, and they run just fine. Don't know why this one gives errors

**Comment by lifehackerhansol** [comment]
Looking at the icon/title information, it seems French and German title information only has two lines, whereas the rest only have 3. 
I made the assumption that they'd all have 3 lines, or two lines, but not a mix. Which is why this error comes up.

I'll have to figure out a way to correctly identify this. Thanks for the report.
